#!/usr/bin/env bash
#server outputs "Hello World!" when queried
#returns a 301 status error when site isn't available

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_conf="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default
service nginx restart
