#!/usr/bin/env bash
#added a custom 404 page

link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_conf="server_name _;\n\trewrite ^/redirect_me/$ $link permanent;"

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page." > /var/www/html/404.html
echo "Holberton School" > /var/www/html/index.html
sed -i "s|server_name\ _;|$new_conf|" /etc/nginx/sites-available/default
service nginx restart

