#!/usr/bin/env bash
# Install and configure HAProxy

apt-get -y install software-properties-common
apt-get -y update
apt-get -y install haproxy

# Configure HAProxy
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        mode http
        server 12656-web-01 52.23.212.186:80
        server 12656-web-02 3.89.155.70:80" > /etc/haproxy/haproxy.cfg

# Restart HAProxy service
systemctl restart haproxy
