#!/usr/bin/env bash
#this scrpt uses the while loop and case statement

i="1"
while [ $i -lt 21 ]
do
        case $i in
                4)
                        echo "bad luck from China"
                        i=$((i+1))
			;;
                9)
                        echo "bad luck from Japan"
                        i=$((i+1))
			;;
                17)
                        echo "bad luck from Italy"
                        i=$((i+1))
			;;
                *)
                        echo "$i"
			i=$((i+1))
			;;
	esac
done
