#!/usr/bin/env bash
#this script gives more information about the SCHOOL file

filee="school"
if [ -e "$filee" ]
then
	echo "school file exists"
	if [ ! -s "$filee" ]
	then
		echo "school file is empty"
	else [ -s "$filee" ] 
		echo "school file is not empty"
	fi
	
        if [ -f "$filee" ]
	then
		echo "school is a regular file"
	fi

else [ ! -e "$filee" ] 
	echo "school file does not exist"
fi
